### ISSUE TITLE
How alive is this project?

### ISSUE THREAD

**Issue by tinnick** [chinedufn/percy#143]
Hi, I found this project from a youtube video. I'm very interested in this project but it doesn't seem to be very active. What's the current status of this project? 

Many thanks,
tinnick

**Comment by chinedufn** [comment]
Hey @tinnick 

Great question.

I'm using it in production for the website for a game that I'm working on https://akigi.com

I pretty much work on that project everyday, but my contributions to Percy only happen when I'm working on the website - or when someone opens an issue / PR I try to get back to it fairly quickly.

At some point later this year I'll need to add more functionality to the website - at which point Percy will get a batch of love. At the top of my list is moving towards state being managed by something similar to [specs](https://github.com/amethyst/specs) / [shred](https://github.com/amethyst/shred).

---

So - to answer your question more concisely.

- Percy is powering a project that I plan to be working on for years to come.

- My frequency of contributions to Percy just depends on whether I'm working on the Akigi website at the time, or if someone opens an issue with a problem that needs to be addressed

- Other people's issues with Percy are my issues, because I use it in production and want it to become a great dev-experience over the years to come. So if someone uses it in its current early / young stage they'll definitely get their issues and PRs answered.

---

Does that answer your question?

Thanks for asking!

**Comment by tinnick** [comment]
@chinedufn Wow! Thank you so much for the thoughtful reply! (and sorry for the late response... I've been sick. (not corona virus))

I don't know if you're aware of [smithy](https://www.smithy.rs/) but it has my interest as well. I'm not very sure if these two completely relate either but I'd like to know your thoughts as well as others about the differences in each *frameworks approach.

I like what percy looks like. It looks more pleasing to me but I haven't played with it enough to know where the devide is...

Many thanks, 
tinnick

**Comment by chinedufn** [comment]
I'm unfamiliar with smithy unfortunately - but it looks pretty cool!

One important thing for me is server side rendering since I'm using Percy for both websites (where SSR tends to be valuable) and web applications (where SSR matters less).

So for my own use cases any toolkit that doesn't have server side rendering support is a non starter.

But I haven't used smithy so I can't give you too much insight unfortunately. I'd say to just give both a spin and then keep pushing forwards with whichever one you're jiving with.

I'll close this issue as I think the original question was addressed, but still feel free to ask any other questions you might have in this issue.

Cheers!
