### ISSUE TITLE
Proc macro parsing example

### ISSUE THREAD

**Issue by dtolnay** [chinedufn/percy#37]
As we talked about at Rust Belt Rust -- here is some demo code of a procedural macro that can parse html tags without a comma required after attribute values:

```rust
// [package]
// name = "html_macro"
// version = "0.0.0"
// edition = "2018"
//
// [lib]
// proc-macro = true
//
// [dependencies]
// syn = { version = "0.15", features = ["full", "extra-traits"] }
// proc-macro2 = "0.4"

extern crate proc_macro;

use proc_macro2::{TokenStream, TokenTree};
use syn::parse::{Parse, ParseStream, Result};
use syn::{parse_macro_input, Expr, Ident, Token};

#[derive(Debug)]
struct Html {
    // TODO: also support content between the tags
    tags: Vec<Tag>,
}

#[derive(Debug)]
enum Tag {
    /// `<div id="app" class=*CSS>`
    Open {
        name: Ident,
        attrs: Vec<Attr>,
    },
    /// `</div>`
    Close {
        name: Ident,
    },
}

#[derive(Debug)]
struct Attr {
    key: Ident,
    value: Expr,
}

impl Parse for Html {
    fn parse(input: ParseStream) -> Result<Self> {
        let mut tags = Vec::new();

        while !input.is_empty() {
            let tag: Tag = input.parse()?;
            tags.push(tag);
        }

        Ok(Html { tags })
    }
}

impl Parse for Tag {
    fn parse(input: ParseStream) -> Result<Self> {
        input.parse::<Token![<]>()?;
        let optional_close: Option<Token![/]> = input.parse()?;
        let is_close_tag = optional_close.is_some();
        let name: Ident = input.parse()?;

        let mut attrs = Vec::new();
        while input.peek(Ident) && !is_close_tag {
            let key: Ident = input.parse()?;
            input.parse::<Token![=]>()?;

            let mut value_tokens = TokenStream::new();
            loop {
                let tt: TokenTree = input.parse()?;
                value_tokens.extend(Some(tt));

                let peek_end_of_tag = input.peek(Token![>]);
                let peek_start_of_next_attr = input.peek(Ident) && input.peek2(Token![=]);
                if peek_end_of_tag || peek_start_of_next_attr {
                    break;
                }
            }

            let value: Expr = syn::parse2(value_tokens)?;
            attrs.push(Attr { key, value });
        }

        input.parse::<Token![>]>()?;

        if is_close_tag {
            Ok(Tag::Close { name })
        } else {
            Ok(Tag::Open { name, attrs })
        }
    }
}

#[proc_macro]
pub fn html(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
    let parsed = parse_macro_input!(input as Html);

    // TODO: produce output data structure using `quote!`
    println!("{:#?}", parsed);
    proc_macro::TokenStream::new()
}
```

Here is the input I was testing with:

```rust
#![feature(proc_macro_hygiene)]

use html_macro::html;

fn main() {
    html! { <div id="app" class=*CSS></div> }
}
```

**Comment by chinedufn** [comment]
OH MY GOODNESS this nearly brought a tear to my eye. Thanks so much for the demo code - this is an unbelievable starting point.

Alright so I'll use this as a starting point, and get the [existing html! macro tests](https://github.com/chinedufn/percy/blob/4ba6842622072a18d2fbe1df5b0fc5ad1d623fb8/crates/virtual-dom-rs/src/html_macro.rs#L274-L416) passing one by one without commas.. extending your demo code as I go.

S W E E T I can't overstate how wildly helpful this it

**Comment by chinedufn** [comment]
@dtolnay so I started working on this and here's where I got stuck:

I build an `Html` struct but wanted to turn it into a `VirtualNode`. This is straightforwards, but since `VirtualNode` doesn't implement `ToTokens` I can't simply do

```rust
quote! {
  #virtual_node
}
```

---

So my question is... Should I implement `ToTokens` for VirtualNode?

OR

Could I instead make the proc macro do nothing but insert commas after attributes?

Then you could write 

`html! { <div id="app" class=*CSS></div> }`

Then the proc macro would generate these tokens:

`html! { <div id="app", class=*CSS,></div> }`

Then I'd quote these new tokens

```rust
quote! { html_macro_rules! { #tokens_with_commas } }
```

And then my currently existing macro rules would handle the parsing.

---

The first solution sounds a bit cleaner / more correct.. while they latter solution seems a little easier.

---

My question as I dive into solution 1 (implement ToTokens).. would there be any consequences to going with option 2 (just inserting commas and then passing the tokens along to my already working macro)?

**Comment by dtolnay** [comment]
Either of those would work. I suspect emitting a call to the macro_rules with commas is only easier because your macro_rules implementation already exists. If you were writing this from scratch I would recommend generating the output code directly from the proc macro (your solution 1) which would be easier to understand and extend.

Regarding ToTokens, generally try to avoid doing any "logic" in ToTokens. It is meant for rendering a syntax tree node to tokens. For example, identifiers and types are syntax tree nodes.

```rust
quote! {
    struct Wrapper {
        #a_field_name: #some_type,
    }

    impl Wrapper {
        fn new(x: #some_type) -> Self {
            Wrapper { #a_field_name: x }
        }
    }
}
```

If your data structure is not "a syntax tree node" i.e. if there is not a 100% obvious behavior for ToTokens that anybody looking at the type would be able to guess with certainty, then write the logic as a non-trait function instead.

```rust
fn build_virtual_node(html: &Html) -> TokenStream {
    /* ... */
}
```

**Comment by chinedufn** [comment]
> Either of those would work. I suspect emitting a call to the macro_rules with commas is only easier because your macro_rules implementation already exists.

Totally.

---

> For example, identifiers and types are syntax tree nodes.

Ahhh I see! That example is useful.

The only place I foresee myself potentially getting tripped up is the recursive nature of a `VirtualNode`.

```
VirtualNode {
  ...
  children: Vec<VirtualNode>
  ...
}
```

But I'll dive in using your advice.. feel it out a bit.. and maybe ping ya one more time if I do indeed get stuck.

THANKS!

**Comment by shakyShane** [comment]
https://github.com/bodil/typed-html

**Comment by chinedufn** [comment]
@qm3ster I'm thinking that we can use it as a great reference implementation but not necessarily be as strict

**Comment by qm3ster** [comment]
Or even PR it there as an opt-in feature, so they have to maintain it :smiling_imp: 
We can justify that by [browsers enabling `custom elements` without flags](https://caniuse.com/#feat=custom-elementsv1) nowadays.
*shakes fist at MS Edge*

**Comment by chinedufn** [comment]
Progress on the procedural macro can be followed here followed here https://github.com/chinedufn/percy/compare/proc-macro

**Comment by chinedufn** [comment]
@dtolnay so I'm working on support for blocks and getting a bit stuck

```rust
html! {
  <div>
    { html! { <span></span> } }
    { child_2 }
  </div>
}
```

The approach that I was going for was

1. Peek to see an open brace.

2. Continue parsing tokens into a `block_tokens: TokeStream` until I see the corresponding closing brace

3. Parse that block as an expression `let expr: Expr = syn::parse2(block_tokens);

4. Use quote to say `quote! { VirtualNode::from(#expr) }`

---

Sounded good in my head, but I got stuck at step one since the following doesn't work.

`Token![{]`.

It it possible to parse a `{` token? 

If not... Is there an easier way to parse a block? I've tried looking through the syn docs / issues but don't quite see how to do it.

Cheers!!

**Comment by dtolnay** [comment]
Check out https://docs.rs/syn/0.15/syn/macro.braced.html in which the example shows how to parse braced struct fields. Another example would be how we parse braced function bodies: https://github.com/dtolnay/syn/blob/0.15.26/src/item.rs#L1080.

**Comment by chinedufn** [comment]
Ohhhh I see. Exactly what I needed - thanks!

**Comment by chinedufn** [comment]
Alright I've got everything working (and learned a ton about syn/quote/proc_macro2 !!!)

Thanks again for the guidance. Could not have gotten things working without you...

Need to clean up / comment and PR but closing this example in the meantime since I don't need it anymore.

**Comment by chinedufn** [comment]
Ahhh ran into a bug looks like I have another question if you don't mind.

I want to know if the next token is a block or open curly brace (either is fine.. whatever is easier).

Here's an illustration of what I mean:

```rust
// Illustration
let content;
let maybe_brace: Option<syn::token::Brace> = braced!(content in input);
```

That of course doesn't work since `braced!` doesn't return an `Option`

Is there another approach that might work here?
