### ISSUE TITLE
Add more <input> examples

### ISSUE THREAD

**Issue by qthree** [chinedufn/percy#41]
It's straightforward to use `<input type="button">`, but what about `text`, `radio` or `checkbox`? How to read `value` on `oninput`? Is there way to get event and event target inside function attached to `oninput`?
I placed such code in global callback inside client crate:
```rust
app.store.borrow_mut().subscribe(Box::new({
    move || {                
        web_sys::console::log_1(&JsValue::from("Updating state"));
        let s_tag = web_sys::window().unwrap().document().unwrap()
            .get_element_by_id("text_input").unwrap();
        let s_tag: web_sys::HtmlInputElement = s_tag.dyn_into().unwrap();
        let value = s_tag.value();
        *app_store_text_field_rc.borrow_mut() = value;
        global_js.update();
    }
}));
```
But it looks more like temporary hack, so what's the proper way?

**Comment by chinedufn** [comment]
So I've just been adding features to Pecy as I've needed them for some sites that I'm working on or as other people have needed them.
So our event story is still a work in progress.

---

I'm curious about what you think would be ideal here?

---

Would something like generally work for you / feel correct?

```rust
let input = html! { 
  <input type="text", !oninput=|mouse_event|  {
   //...
  },></input>
  };
```

I think we might be able to do this pretty easily (emphasis on think.. I'm just going off the top of my head..)

Here's what I'm thinking:

---

Right now we store our events as wasm-bindgen `Closure`'s 

https://github.com/chinedufn/percy/blob/d968875fca97cc3bdae5ace48964f0d9458c5b74/crates/virtual-dom-rs/src/virtual_node/mod.rs#L346

This prevents us from being able to have different events with different arguments since we're clearly specifying `Fn() -> ()` there.

If we instead stored `Function`'s we could have whatever signatures we wanted.

So instead of converting the callback into a `Function` here

https://github.com/chinedufn/percy/blob/d968875fca97cc3bdae5ace48964f0d9458c5b74/crates/virtual-dom-rs/src/virtual_node/mod.rs#L184

We'd convert it here, right before adding it to the `VirtualNode` (using `unchecked_into` instead of `unchecked_ref` I think..?

https://github.com/chinedufn/percy/blob/d968875fca97cc3bdae5ace48964f0d9458c5b74/crates/virtual-dom-rs/src/html_macro.rs#L192

Then `Events` here 

https://github.com/chinedufn/percy/blob/master/crates/virtual-dom-rs/src/virtual_node/mod.rs

would probably change to store `Function` instead of `Closure`

---

Curious about your thoughts here! If this implementation makes sense I've be more than happy to help walk you through it / answer absolutely any questions.

Otherwise I've already set aside time 2 weeks from now to work on Percy's router and re-writing the `html!` macro as a procedural macro so I could also address this at that time.

At any rate.. Thanks a lot for opening up this issue! Keep them coming! We definitely want to prioritize things that people need right now so this is great.

**Comment by chinedufn** [comment]
Ok so I actually started taking a look at this and it's slightly more complicated than I laid out.

I'll think a bit and get back to ya

**Comment by chinedufn** [comment]
Ok I think the way to go here is to just add macro rules for each type of input

`oninput` `ontext`.. etc

There's a finite number that isn't very large. If someone needs a custom event listener they can use the old `!myevent = || {}` syntax.

I'll get a unit test and implementation for this in a PR and tag you. Then we can use that as an example for adding new events over time as we need them!

**Comment by chinedufn** [comment]
Alright the codes messy and a work in progress but I have a branch with a failing test case

![image](https://user-images.githubusercontent.com/2099811/48271531-87907f80-e40a-11e8-9ae2-90c0f742a66d.png)

![image](https://user-images.githubusercontent.com/2099811/48271575-9f680380-e40a-11e8-88ac-b79949796256.png)

https://github.com/chinedufn/percy/commit/51d6463969d0aaf746f0ee531c4b5d774d04ff8a

I Should have time this weekend to get this working

Again.. code isn't cleaned up at all just sharing the progress
