### ISSUE TITLE
Access to Events in handlers (virtual DOM)

### ISSUE THREAD

**Issue by agrif** [chinedufn/percy#44]
Unless I'm mistaken, there isn't currently any way to access the event itself inside event handlers.

It looks like some support for this was added recently for `oninput`, and I think that route is maybe a bit labor intensive but worth pursuing.

However, in the meantime, would it be possible to let generic handlers access their event? Either as a [Event](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.Event.html) struct, or an even more generic JsValue. This maybe isn't a very pleasant API, but it would be a quick win, and let us actually inspect the events for things like keycodes that aren't available any other way.

**Comment by chinedufn** [comment]
I’m on mobile for the weekend so forgive any typos

So the !myevent closure would have one Event parameter and then you could just convert it into any other type of event that you wanted?

That makes a lot of sense to me and I a pretty quick win. 

We’d just need to update https://github.com/chinedufn/percy/blob/master/crates/virtual-node/src/lib.rs#L386 to be FnMut(Event)

Interested in taking a stab at this? I’d be happy to answer any questions!

Otherwise I should be back to my machine later this weekend and I can take a look!

**Comment by agrif** [comment]
I'll give it a look, but I'm working on some other things right now too. If you find the time first, go on ahead!

**Comment by chinedufn** [comment]
@agrif thanks for raising the issue!

You can now you any `web_sys::*` event that you please. Ended up just storing the `Closure`'s dynamically with some help from https://github.com/rustwasm/wasm-bindgen/issues/1140#issuecomment-450668813

Commit -> https://github.com/chinedufn/percy/commit/ab4e8c31e3c7bb168b7cd92bb5081efc900cb037

example:

```
html! { <div !onclick=|ev: web_sys::MouseEvent| {}></div>
```
