### ISSUE TITLE
Unexpected element nesting

### ISSUE THREAD

**Issue by richardanaya** [chinedufn/percy#57]
Noticing issues where elements will be nested in previous elements

```
<div>
    <section>{"foo"}</section>
   <section>{"bar"}</section>
</div>
```
will result in:
```
<div>
   <section>
       foo
       <section>bar</section>
   </section>
</div>
```

**Comment by chinedufn** [comment]
Hmmm

If you're interested in contributing I'd be happy to answer any questions. I'd start by [adding a failing test case here](https://github.com/chinedufn/percy/blob/8f680a30c2f4b0a5e506e3f29667fe4a31f165eb/crates/virtual-dom-rs/src/html_macro.rs#L392)

Otherwise, no worries, I'll make some time to look at this soon!

**Comment by chinedufn** [comment]
Alright I think I have some time to that a look at this.

Was this during server side rendering on was this the result of a virtual dom patch?

**Comment by chinedufn** [comment]
Need a little more information so closing in the meantime!
