### ISSUE TITLE
Unable to run example

### ISSUE THREAD

**Issue by hmobrienv** [chinedufn/percy#6]
Fairly new to Rust so might be missing something simple. Running the example fails with the following errors,

> warning: unused manifest key: package.private
> warning: unused manifest key: package.private
>    Compiling itoa v0.4.2
>    Compiling dtoa v0.4.3
>    Compiling serde v1.0.70
>    Compiling syn v0.14.5
> error[E0463]: can't find crate for `std`
>   |
>   = note: the `wasm32-unknown-unknown` target may not be installed
> 
> error: aborting due to previous error
> 
> For more information about this error, try `rustc --explain E0463`.
> error[E0463]: can't find crate for `std`
>   |
>   = note: the `wasm32-unknown-unknown` target may not be installed
> 
> error: aborting due to previous error
> 
> For more information about this error, try `rustc --explain E0463`.
> error: Could not compile `dtoa`.
> warning: build failed, waiting for other jobs to finish...
> error: Could not compile `itoa`.
> warning: build failed, waiting for other jobs to finish...
> error[E0463]: can't find crate for `std`
>   |
>   = note: the `wasm32-unknown-unknown` target may not be installed
> 
> error: aborting due to previous error
> 
> For more information about this error, try `rustc --explain E0463`.
> error: Could not compile `serde`.
> warning: build failed, waiting for other jobs to finish...
> error: build failed
> warning: unused manifest key: package.private
> warning: unused manifest key: package.private
>    Compiling proc-macro2 v0.4.9
> error[E0433]: failed to resolve. Could not find `Punct` in `proc_macro`
>    --> /Users/mobrien/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.4.9/src/unstable.rs:131:42
>     |
> 131 |                 let mut op = proc_macro::Punct::new(tt.as_char(), spacing);
>     |                                          ^^^^^ Could not find `Punct` in `proc_macro`
> 
> error[E0433]: failed to resolve. Could not find `Ident` in `proc_macro`
>    --> /Users/mobrien/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.4.9/src/unstable.rs:468:60
>     |
> 468 |             Span::Nightly(s) => Ident::Nightly(proc_macro::Ident::new(string, s)),
>     |                                                            ^^^^^ Could not find `Ident` in `proc_macro`
> 
> error[E0433]: failed to resolve. Could not find `Ident` in `proc_macro`
>    --> /Users/mobrien/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.4.9/src/unstable.rs:475:60
>     |
> 475 |             Span::Nightly(s) => Ident::Nightly(proc_macro::Ident::new_raw(string, s)),
>     |                                                            ^^^^^ Could not find `Ident` in `proc_macro`
> 
> error[E0412]: cannot find type `Ident` in module `proc_macro`
>    --> /Users/mobrien/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.4.9/src/unstable.rs:461:25
>     |
> 461 |     Nightly(proc_macro::Ident),
>     |                         ^^^^^ not found in `proc_macro`
> help: possible candidates are found in other modules, you can import them into scope
>     |
> 3   | use Ident;
>     |
> 3   | use imp::Ident;
>     |
> 3   | use stable::Ident;
>     |
> 
> error[E0412]: cannot find type `Ident` in module `proc_macro`
>    --> /Users/mobrien/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.4.9/src/unstable.rs:495:44
>     |
> 495 |     fn unwrap_nightly(self) -> proc_macro::Ident {
>     |                                            ^^^^^ not found in `proc_macro`
> help: possible candidates are found in other modules, you can import them into scope
>     |
> 3   | use Ident;
>     |
> 3   | use imp::Ident;
>     |
> 3   | use stable::Ident;
>     |
> 
> error[E0554]: #![feature] may not be used on the stable release channel
>   --> /Users/mobrien/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.4.9/src/lib.rs:47:34
>    |
> 47 | #![cfg_attr(feature = "nightly", feature(proc_macro_raw_ident, proc_macro_span))]
>    |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> error: aborting due to 6 previous errors
> 
> Some errors occurred: E0412, E0433, E0554.
> For more information about an error, try `rustc --explain E0412`.
> error: Could not compile `proc-macro2`.
> 
> To learn more, run the command again with --verbose.

**Comment by hmobrienv** [comment]
Resolved the errors related to proc-macro2 and wasm32-unknown-unknown,

Install and use rust nightly toolchain as default,

`$ rust install nightly && rust default nightly`

and,

`$ rustup target add wasm32-unknown-unknown`

Running the example still fails with, 

> warning: unused manifest key: package.private
> warning: unused manifest key: package.private
>    Compiling isomorphic-app v0.1.0 (file:///Users/mobrien/projects/percy/examples/isomorphic/app)
> error[E0432]: unresolved import `virtual_dom_rs::webapis`
>   --> examples/isomorphic/app/src/lib.rs:17:25
>    |
> 17 | pub use virtual_dom_rs::webapis::*;
>    |                         ^^^^^^^ Could not find `webapis` in `virtual_dom_rs`
> 
> error[E0412]: cannot find type `Element` in this scope
>   --> examples/isomorphic/app/src/lib.rs:59:46
>    |
> 59 |     pub fn update_dom(&mut self, root_node: &Element) {
>    |                                              ^^^^^^^ not found in this scope
> 
> warning: unused import: `std::cell::Cell`
>  --> examples/isomorphic/app/src/lib.rs:9:5
>   |
> 9 | use std::cell::Cell;
>   |     ^^^^^^^^^^^^^^^
>   |
>   = note: #[warn(unused_imports)] on by default
> 
> warning: unused import: `std::cell::RefCell`
>  --> examples/isomorphic/app/src/state.rs:7:5
>   |
> 7 | use std::cell::RefCell;
>   |     ^^^^^^^^^^^^^^^^^^
> 
> error: aborting due to 2 previous errors
> 
> Some errors occurred: E0412, E0432.
> For more information about an error, try `rustc --explain E0412`.
> error: Could not compile `isomorphic-app`.
> 
> To learn more, run the command again with --verbose.
> warning: unused manifest key: package.private
> warning: unused manifest key: package.private
>    Compiling isomorphic-app v0.1.0 (file:///Users/mobrien/projects/percy/examples/isomorphic/app)
> error[E0432]: unresolved import `virtual_dom_rs::webapis`
>   --> examples/isomorphic/app/src/lib.rs:17:25
>    |
> 17 | pub use virtual_dom_rs::webapis::*;
>    |                         ^^^^^^^ Could not find `webapis` in `virtual_dom_rs`
> 
> error[E0412]: cannot find type `Element` in this scope
>   --> examples/isomorphic/app/src/lib.rs:59:46
>    |
> 59 |     pub fn update_dom(&mut self, root_node: &Element) {
>    |                                              ^^^^^^^ not found in this scope
> 
> warning: unused import: `std::cell::Cell`
>  --> examples/isomorphic/app/src/lib.rs:9:5
>   |
> 9 | use std::cell::Cell;
>   |     ^^^^^^^^^^^^^^^
>   |
>   = note: #[warn(unused_imports)] on by default
> 
> warning: unused import: `std::cell::RefCell`
>  --> examples/isomorphic/app/src/state.rs:7:5
>   |
> 7 | use std::cell::RefCell;
>   |     ^^^^^^^^^^^^^^^^^^
> 
> error: aborting due to 2 previous errors
> 
> Some errors occurred: E0412, E0432.
> For more information about an error, try `rustc --explain E0412`.
> error: Could not compile `isomorphic-app`.
> 
> To learn more, run the command again with --verbose.

**Comment by parweb** [comment]
#metoo

**Comment by chinedufn** [comment]
Apologies!! Just pushed a fix to the master branch.

Please feel free to re-open if you have any other issues!

**Comment by parweb** [comment]
` percy git:(master) git pull origin`

`percy git:(master) ./examples/isomorphic/start.sh`

`error: no such subcommand: `+nightly`
warning: unused manifest key: package.private
warning: unused manifest key: package.private
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading wasm-bindgen v0.2.15
 Downloading wasm-bindgen-macro v0.2.15
 Downloading wasm-bindgen-shared v0.2.15
 Downloading wasm-bindgen-backend v0.2.15
   Compiling wasm-bindgen-shared v0.2.15
   Compiling proc-macro2 v0.4.9
error[E0433]: failed to resolve. Could not find `Group` in `proc_macro`
   --> /Users/parweb/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.4.9/src/unstable.rs:122:45
    |
122 |                 let mut group = proc_macro::Group::new(delim, tt.stream.inner.unwrap_nightly());
    |                                             ^^^^^ Could not find `Group` in `proc_macro`

error[E0433]: failed to resolve. Could not find `Punct` in `proc_macro`
   --> /Users/parweb/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.4.9/src/unstable.rs:131:42
    |
131 |                 let mut op = proc_macro::Punct::new(tt.as_char(), spacing);
    |                                          ^^^^^ Could not find `Punct` in `proc_macro`

error[E0433]: failed to resolve. Could not find `token_stream` in `proc_macro`
   --> /Users/parweb/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.4.9/src/unstable.rs:213:25
    |
213 |     Nightly(proc_macro::token_stream::IntoIter),
    |                         ^^^^^^^^^^^^ Could not find `token_stream` in `proc_macro`

error[E0433]: failed to resolve. Could not find `Ident` in `proc_macro`
   --> /Users/parweb/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.4.9/src/unstable.rs:468:60
    |
468 |             Span::Nightly(s) => Ident::Nightly(proc_macro::Ident::new(string, s)),
    |                                                            ^^^^^ Could not find `Ident` in `proc_macro`

error[E0433]: failed to resolve. Could not find `Ident` in `proc_macro`
   --> /Users/parweb/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.4.9/src/unstable.rs:475:60
    |
475 |             Span::Nightly(s) => Ident::Nightly(proc_macro::Ident::new_raw(string, s)),
    |                                                            ^^^^^ Could not find `Ident` in `proc_macro`

error[E0412]: cannot find type `Ident` in module `proc_macro`
   --> /Users/parweb/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.4.9/src/unstable.rs:461:25
    |
461 |     Nightly(proc_macro::Ident),
    |                         ^^^^^ not found in `proc_macro`
help: possible candidates are found in other modules, you can import them into scope
    |
3   | use Ident;
    |
3   | use imp::Ident;
    |
3   | use stable::Ident;
    |

error[E0412]: cannot find type `Ident` in module `proc_macro`
   --> /Users/parweb/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.4.9/src/unstable.rs:495:44
    |
495 |     fn unwrap_nightly(self) -> proc_macro::Ident {
    |                                            ^^^^^ not found in `proc_macro`
help: possible candidates are found in other modules, you can import them into scope
    |
3   | use Ident;
    |
3   | use imp::Ident;
    |
3   | use stable::Ident;
    |

error[E0554]: #![feature] may not be used on the stable release channel
  --> /Users/parweb/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.4.9/src/lib.rs:47:34
   |
47 | #![cfg_attr(feature = "nightly", feature(proc_macro_raw_ident, proc_macro_span))]
   |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 8 previous errors

Some errors occurred: E0412, E0433, E0554.
For more information about an error, try `rustc --explain E0412`.
error: Could not compile `proc-macro2`.
warning: build failed, waiting for other jobs to finish...
error: build failed`

**Comment by chinedufn** [comment]
> error: no such subcommand:+nightly

Ah it looks like you aren't on nightly Rust, so changing that should solve the problem here!

If you don't already have it - [install rustup](https://rustup.rs/)

Then `rustup install nightly`

And you should be off to the races!

Please feel free to re-open if that doesn't work for you!
