### ISSUE TITLE
Can we do without 'diffing'?

### ISSUE THREAD

**Issue by nexar** [chinedufn/percy#85]
This is not an 'issue' but a question about a particular approach.

Let me start by saying that I'm a complete newb on Rust/Wasm and am just looking around to see how this new eco system works and whether I can use it on a project that I'm considering.

As part of this research I first came across Yew and then following various rabbit holes found Percy.  So far Percy's approach to me seems easier however there is one part of Yew which I thought was particularly good.  Yew has a concept of 'ShoudRender' for each component which when set to 'true' renders that component.  

I was wondering whether you had considered this approach and what reasons you had for rejecting it, because that takes away the whole need to do any 'diffing' and leaves the responsibility firmly in the user's lap for when a component should be (re)rendered.

**Comment by chinedufn** [comment]
@nexar welcome to the Rust/Wasm world!

I haven't used Yew, but I don't think that `ShouldRender` allows you to avoid diffing entirely.

Insteead, I think (haven't looked at the code) the flow is more like this:

- If should render is false, don't bother diffing or patching the DOM since the developer is saying that they are sure that nothing has changed

- if should render is true, run a diff. Then if something changed -> patch the DOM.

---

Having more fine grained control over things like whether or not to update a component.. Or lifecycle hooks such as a callback when a component is first added into the DOM is planned for Percy but it just hasn't been worked on yet!

---

But, to be clear, `ShouldRender` really just means "should we attempt to diff/patch the DOM again or should we just skip that because you as the developer are saying that you're certain that nothing has changed".

---

Let me know if that helps or if I can clarify anything else!

**Comment by nexar** [comment]
@chinedufn thanks very much for the quick response.  I went back to the Yew docs and yes you are right the ShouldRender only allows them to skip diffing not remove it's need entirely. 

Very much appreciate the clarification.
